//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antilles.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("leer")]
        public string AntennahouseLocation {
            get {
                return ((string)(this["AntennahouseLocation"]));
            }
            set {
                this["AntennahouseLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("leer")]
        public string RenderXLocation {
            get {
                return ((string)(this["RenderXLocation"]));
            }
            set {
                this["RenderXLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fop")]
        public string FoFormatierer {
            get {
                return ((string)(this["FoFormatierer"]));
            }
            set {
                this["FoFormatierer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KeepFoFiles {
            get {
                return ((bool)(this["KeepFoFiles"]));
            }
            set {
                this["KeepFoFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool saxon_sall {
            get {
                return ((bool)(this["saxon_sall"]));
            }
            set {
                this["saxon_sall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool saxon_signorable {
            get {
                return ((bool)(this["saxon_signorable"]));
            }
            set {
                this["saxon_signorable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool saxon_snone {
            get {
                return ((bool)(this["saxon_snone"]));
            }
            set {
                this["saxon_snone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool saxon_ds {
            get {
                return ((bool)(this["saxon_ds"]));
            }
            set {
                this["saxon_ds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool saxon_dt {
            get {
                return ((bool)(this["saxon_dt"]));
            }
            set {
                this["saxon_dt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool saxon_w0 {
            get {
                return ((bool)(this["saxon_w0"]));
            }
            set {
                this["saxon_w0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool saxon_w1 {
            get {
                return ((bool)(this["saxon_w1"]));
            }
            set {
                this["saxon_w1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool saxon_w2 {
            get {
                return ((bool)(this["saxon_w2"]));
            }
            set {
                this["saxon_w2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool saxon_versionwarn {
            get {
                return ((bool)(this["saxon_versionwarn"]));
            }
            set {
                this["saxon_versionwarn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Schematronberichtbrowser {
            get {
                return ((bool)(this["Schematronberichtbrowser"]));
            }
            set {
                this["Schematronberichtbrowser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cals2htmlberichtbrowser {
            get {
                return ((bool)(this["Cals2htmlberichtbrowser"]));
            }
            set {
                this["Cals2htmlberichtbrowser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool XMLdarstellenbrowser {
            get {
                return ((bool)(this["XMLdarstellenbrowser"]));
            }
            set {
                this["XMLdarstellenbrowser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool saxon_l {
            get {
                return ((bool)(this["saxon_l"]));
            }
            set {
                this["saxon_l"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool saxon_timing {
            get {
                return ((bool)(this["saxon_timing"]));
            }
            set {
                this["saxon_timing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool saxon_explain {
            get {
                return ((bool)(this["saxon_explain"]));
            }
            set {
                this["saxon_explain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool saxon_traceextfunct {
            get {
                return ((bool)(this["saxon_traceextfunct"]));
            }
            set {
                this["saxon_traceextfunct"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool saxon_xml11 {
            get {
                return ((bool)(this["saxon_xml11"]));
            }
            set {
                this["saxon_xml11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool antilles_wellformedcheck {
            get {
                return ((bool)(this["antilles_wellformedcheck"]));
            }
            set {
                this["antilles_wellformedcheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool antilles_willkommensbild {
            get {
                return ((bool)(this["antilles_willkommensbild"]));
            }
            set {
                this["antilles_willkommensbild"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("unset")]
        public string antilles_arbeitsordner {
            get {
                return ((string)(this["antilles_arbeitsordner"]));
            }
            set {
                this["antilles_arbeitsordner"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>c:/</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Historie {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Historie"]));
            }
            set {
                this["Historie"] = value;
            }
        }
    }
}
